#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    TheSkyX_Path=`/usr/bin/find /Applications -maxdepth 3 -name TheSkyX\*.app`
    if [ -d "$TheSkyX_Path" ]; then
		TheSkyX_Path="${TheSkyX_Path}/Contents"
    else
	   echo TheSkyX application was not found.
    	exit 1
	 fi
else
	TheSkyX_Path=$(<"$TheSkyX_Install")
fi

echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

echo "Installing in $PLUGINS_DIR/MountPlugIns/"

cp -f "/tmp/Skywatcher_X2/mountlist Skywatcher.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp -f "/tmp/Skywatcher_X2/Skywatcher.ui" "$PLUGINS_DIR/MountPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp -f "/tmp/Skywatcher_X2/libSkywatcher.dylib" "$PLUGINS_DIR/MountPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/mountlist Skywatcher.txt"
	chown $app_owner "$PLUGINS_DIR/Skywatcher.ui"
	chown $app_owner "$PLUGINS_DIR/libSkywatcher.dylib"
fi
chmod 644 "$TheSkyX_Path/Resources/Common/Miscellaneous Files/mountlist Skywatcher.txt"
chmod 644 "$PLUGINS_DIR/Skywatcher.ui"
chmod 755 "$PLUGINS_DIR/libSkywatcher.dylib"

rm -rf /tmp/Skywatcher_X2

